(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.WFM_Logo_White_RGBai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKgALSMVIgBANQAAAPAKAAIAzAAQAMAAgBAKIAACUQAAAHAGACQADACAKABQAKgBAEgCQAFgCAAgIIgBiTQABgKAMAAIAxAAQALAAAAgSQAAgSgMAAIigAAQgGAAgDAIgADSONIBBBGQAHAHATABQANAAAFgFQAGgFgIgIIhOhWQgJgLAKgHIBAg6QAJgKgMgMQgMgMgNALIhKBEQgFAFgEABQgFADgKAAQgKAAAAgOIAAg2QAAgMgRAAQgMAAgDACQgFACgBAIIAAC1QAAANARAAQAVAAAAgNIAAg7QAAgGADgFQAEgEAFAAQATgBALAKgAhwOXQALAAAFAJIAhAyQAFAIARABQAPAAAEgFQAFgEgFgHIgigzQgEgFAHgHQAPgKAIgIQAOgQAAgYQABgfgVgUQgUgSggAAIhsAAQgJAAAAAIIAAC6QAAAMANAAIAPgBQAKgBAAgHIgBgxQABgEADgDQADgDAEAAgAmQOxQAIAAACAHIANAbQAEAHAPABQAIgBAGgCQAJgDgDgGIhXi7QgFgJgLAAQgMAAgEAKIhaC5QgFAMAWAAQASAAADgHIANgXQAEgLAIAAgArGNkIANBsQAAAFAGADQAFADAEAAQAYAAgBgLIgVi2QgCgIgEgDQgDgCgGAAQgLAAgEAIIg8BPQgHAIgEAAQgEABgGgIIg3hPQgGgIgKAAQgKgBgEAFQgDADgCAJIgVCxQAAAGAGADQAFADAFAAQAUAAACgLIANhpQACgIAEABQAEAAADACIAtA9QAEAHAHAAQAFAAAFgGIAwg/QADgEAEABQAFgBACAHgAGyMaIAACwQAAAOANAAICcAAQAKABAAgSQAAgSgKAAIh6AAQgJAAgBgLIAAgdQAAgLAMAAIBFAAQAKAAAAgRQABgTgLABIhHAAQgJAAgBgKIAAgbQAAgJAJAAIB6AAQAHAAADgGQABgEAAgJQAAgJgBgEQgDgEgGAAIicAAQgNAAAAANgAT4IwQgNAOABASQgBASANANQANANATAAQASAAANgNQANgNAAgSQAAgSgNgOQgNgNgSABQgTgBgNANgAP5JKQAlAMA0AAQBUAAAzgtQAygtAAhJQAAghgMgeQgMgegWgXQgUgVgXgSQgWgRgzgkIgqgdQgbgVgMgSQgJgMAAgXQAAgaARgQQASgPAeAAQAsAAAjAbQAPALAFAGQAHAIAOAVQAKAOAMAAQALABAGgHQAIgFgBgJQABgIgCgEIgUhcQgFgXgTAAQgIAAgKAGQgLAIgIAAIgMgCIgWgEQgjgIgmAAQhGAAgrAlQgrAmAAA+QAAAzAgAmQAUAVARAPIBNA3QBBAsAaAdQAcAfgBAhQABAigaAUQgaAWgpAAQglAAgigSQghgTgWgfIgMgRQgJgLgMAAQgLAAgIAIQgIAIAAALQAAAKACAHIAWBUQAEAQAFAHQAGAGALAAQAJAAALgIQAJgJAJABIASAEgAjRF+QAHAAACALIABADQAYBeBFA1QBHA2BlAAQCCAABMhQQBMhRAAiIQAAiFhMhQQhNhQh+ABQhogBhHA3QhFA1gYBgIAAABQgCALgHAAQgIAAgBgKQgYhhhHg2QhHg3hoABQiBAAhLBQQhLBQAACIQgBCFBMBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgLAGAAIABAAgAFnIeQgGAHAAAKQAAANAJAFQAIAEAUADQBeANBrgBQBFABAxgOQAvgOAlgeQAwglAZg+QAZg9AAhOQAAhFgTg3QgVg5glgmQgngng1gSQg1gShOAAQhrAAheANQgUADgIAEQgJAFAAANQAAAJAGAIQAFAGAJABIARAAQAKAAAFALQADAKgBAXIAAF5QABAYgDAKQgFALgKAAIgRAAQgJAAgFAHgAyyIfQgHAHABAKQgBAOAJAFQAJAGAWAAICcAAQAYAAAJgGQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgMAAgGgMQgCgFAAgbIgBiLQAAgZAJgFQAEgEAeAAIBGAAQAaAAAIAEQAHADACANIABAFQAEAWATABQANgBAGgIQAFgKAAgWIAAhHQAAgWgFgJQgGgJgNAAQgUAAgDAVIgBAGQgBAMgIAEQgHADgbAAIhGAAQgeAAgEgDQgJgFAAgaIAAhlQABghAIgJQAJgJAiAAIBtAAQAgAAANAEQAOAFAGAPQAFAOADAFQAIAOAOAAQAMAAAFgJQAGgJgEgQIgMg8QgFgUgZgBIlwAAQgWABgIAFQgJAGAAAOQgBAJAHAHQAHAHAIAAIASAAQAEAAAEAEQAEADABAGQAEAKAAAXIAAF8QAAAXgDAJQgEAMgKAAIgSAAQgJAAgGAGgACorXQACAKgJADQgpAOgmATQgmATgZASQg5AoggBCQgfBEAABaQgBCLBPBTQBOBUCEAAQCHAABQhVQBPhUAAiOQAAilhohNQg7gsg4AGQghAEgFAUQgFATAbAKQA2AUAZA8QAXA3ABBfQAABxgrBBQgrBChKAAQhLAAgphBQgrg/AAhyQAAhQAQg0QASg+AwgvQAegdBHgjQA9gfAigrQATgZABgVQACgTgQgEQgMgEgNANIgZAWQguAeg4gRQgvgPgjgoQgcgggogIQgcgGgfAHQgLADgEgHQgCgHAKgIQAbgVArACQAvACAfAcQAdAbAhAPQAjARAagGQARgDAAgOQABgOgTgHQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBWQgGAXAMALQAMALAUgKQA7gZAuAWQAJAEAhAVQAcARAWAJQAsARA7gLIAGAAQAIAAACAHgAvDlPIBJDYQAHAXALAJQALAKATAAQATAAALgLQAKgLAJggICImzQAGgWAHgJQAIgJALgCQAkgEgBAwIAAF+QAAAbgCAHQgBAEgFADQgEADgFAAIgQAAQgJAAgHAHQgGAHgBAJQAAAOAJAGQAJAFAVAAICbAAQAVAAAIgFQAHgFABgOQAAgKgGgHQgGgHgJAAIgQAAQgLAAgFgKQgCgKAAgYIAAiBQgBgeAGgGQAFgHAYABIBzAAQAYgBAHAIQACAEABAGIAAAeIAAB8QAAAbgCAHQgGAKgJAAIgRAAQgIAAgHAHQgGAHAAAJQgBAOAJAGQAIAFAWAAICaAAQAWAAAJgFQAJgGAAgOQAAgJgHgHQgGgHgKAAIgRAAQgEAAgFgDQgEgDgBgEQgEgKAAgYIAAl+QAAgXAEgKQABgEAEgDQAFgEAEAAIARAAQAKABAGgHQAHgHAAgKQgBgOgIgFQgJgGgWAAIiaAAQgWAAgJAGQgJAFABAOQgBAKAHAHQAGAHAKgBIARAAQAKAAAFALQACAGAAAbIAABpIAAAeQgBAHgCADQgHAHgYAAIhzAAQgYAAgFgGQgGgHABgdIAAhuQAAgYACgJQAFgLALAAIAQAAQAJABAGgHQAGgHAAgKQAAgOgIgFQgIgGgVAAIkmAAQgRAAgIAGQgIAFAAANQAAAWAcABQAeAEAAATQAAAIgEAMIheE7QgCAFgEABQgEAAgCgGIhfksQgIgZgBgLQAAgMAHgEQAFgFARgCQAcgFgBgSQAAgXgcAAIinAAQgdAAgBAaQABAJAFAFQAGAFANADQAOAFAHADQAHAFADAKIAmBtQAHAYgJAZIg+C3QgCAFgEAAQgFABgCgFIh0lIQgCgLAAgIQAAgKAGgFQAGgEAOgCQARgBAGgGQAIgEgBgLQAAgXgcAAIiuAAQgdAAAAAWQAAALAFAEQAFAGANACQAVAFAHAGQAHAIAJAaICnG/QAJAXALAKQAKAJATAAQAQAAAMgJQAIgIAJgZIBOjYQABgGAEAAQAFAAABAGgAOkiCQgGAHAAAJQAAAOAJAGQAHAFAWABIFigBQAaAAAFgVIANhCQADgQgFgJQgEgJgNABQgPAAgHAPIgIAQQgPAggvAAIhUAAQgkAAgPgGQgKgEgDgLQgDgLAAgiIAAhsQAAgZAIgFQAEgDAfAAIAmAAQAbAAAHADQAIADACANIAAAFQAEAXAUAAQANAAAGgJQAEgJAAgWIAAhIQAAgVgEgJQgGgKgNAAQgUAAgEAWIAAAFQgCANgHADQgIADgbAAIgmAAQgfAAgEgCQgIgGAAgaIAAhkQAAgiAIgJQAJgIAjgBIBQAAQAfABANAEQAPAFAFAPQAGAQADACQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgFgVgZAAIlTAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAEAEACAFQADAIAAAaIAAF7QAAAagDAIQgCAEgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgGAHAAAJQAAAOAJAGQAIAFAVAAIE/AAQAaAAAFgVIAMhCQAEgQgFgJQgFgJgMABQgPAAgIAPIgHAQQgQAgguAAIgxAAQgZAAgMgCQgMgBgGgFQgIgFgCgJQgCgJAAgdIAAllQABgbACgFQADgMAOAAIATAAQAJABAHgHQAGgHABgKQgBgOgIgFQgKgGgXAAIicAAQgWAAgJAGQgJAFAAAOQAAAKAHAHQAGAHAKgBIARAAQALAAADAMQADAHAAAZIAAGBQAAAXgDAIQgBAEgEADQgFAEgEAAIgRAAQgJAAgGAGg");
	this.shape.setTransform(175,175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAaQgKgLAAgPQAAgOAKgKQAKgLAOABQAPgBAKALQAKAKAAAOQAAAPgKALQgKAJgPABQgOgBgKgJgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(305.4,234.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(163.9,260);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(305.6,233);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QAog/BHAAQBGAAAoA/QAqBAAABqQAABrgpBAQgpA/hFAAQhIAAgog+g");
	this.shape_4.setTransform(126.2,205.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgyQABgDADAAQADAAACADIAZAzQABADgCACQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(130.7,263.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(239.5,205);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QApg/BGAAQBFAAAqA/QApBAAABqQAABrgpBAQgpA/hGAAQhGAAgpg+g");
	this.shape_7.setTransform(181.9,205.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,350,350);


(lib.price = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAuIgEgBIgCgCIgBgDQAAgCABgDIAFgGIADgGQACgDAAgCIgBgDIgCgBIgFAAIgEgBIgIgEIgHgHIgDgHIgBgJQAAgHACgGQADgGAEgEQAEgEAGgCQAGgDAGAAQAGAAAGADQAGACAFADQAEAEADAGQACAFABAHQAAAHgCAGIgHALIgVAkQgBABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgCABgAgFgeIgGADIgEAGIgBAGIABAHIAEAFIAGADQADACACAAQAEAAADgCIAFgDQACgCABgDIACgHQAAgDgCgDQgBgDgCgDIgFgDQgDgCgEAAQgCAAgDACg");
	this.shape.setTransform(85.8,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgFAuIgCgBIgDgCIgBgDQAAgCACgDIADgGIAFgGQABgDAAgCIAAgDIgDgBIgEAAIgGgBIgHgEIgGgHIgFgHIgBgJQAAgHADgGQACgGAEgEQAFgEAGgCQAGgDAGAAQAGAAAGADQAGACAEADQAFAEADAGQADAFAAAHQgBAHgCAGIgFALIgXAkQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgCABgAgGgeIgFADIgEAGIgBAGIABAHIAEAFIAFADQADACADAAQADAAAEgCIAFgDQADgCABgDIABgHQAAgDgBgDQgBgDgDgDIgFgDQgEgCgDAAQgDAAgDACg");
	this.shape_1.setTransform(78.3,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgFAGQgCgDAAgDQgBgDADgCQACgCADAAQAEAAACACQADACAAADQAAADgDADQgCADgEAAQgDAAgCgDg");
	this.shape_2.setTransform(72.6,3.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgFAuIgCgBIgDgCIgBgDQAAgCACgDIADgGIAFgGQABgDAAgCIAAgDIgDgBIgEAAIgGgBIgHgEIgGgHIgFgHIgBgJQAAgHADgGQACgGAEgEQAFgEAGgCQAGgDAGAAQAGAAAGADQAGACAEADQAFAEADAGQADAFAAAHQgBAHgCAGIgFALIgXAkQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgCABgAgGgeIgFADIgEAGIgBAGIABAHIAEAFIAFADQADACADAAQADAAAEgCIAFgDQADgCABgDIABgHQAAgDgBgDQgBgDgDgDIgFgDQgEgCgDAAQgDAAgDACg");
	this.shape_3.setTransform(67,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAGAsIgDAAIgCgCIgBgCIAAg3IAAgCIgDgBQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCABQgDAAgCgDIgBgFIAAgEIACgCIAEgCIADgDIAFgDIAEgDIAFgCIACgBIADABIABADIAABPQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBABIgDABg");
	this.shape_4.setTransform(60.5,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAHAsIgEAAIgCgCIgBgCIAAg3IAAgCIgDgBQAAAAgBAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCABQgDAAgCgDIgCgFIABgEIACgCIAEgCIADgDIAFgDIAEgDIAFgCIACgBIADABIACADIAABPQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBABIgDABg");
	this.shape_5.setTransform(56.1,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGA8IgBgEIAAgFQAAAAgBgBQAAgBAAAAQAAgBAAAAQgBgBAAAAIgDgCIgCgCIgHgCIgHgDIgGgFQgDgDAAgCIACgDIACgDIADgCIADgBIACABIACAAIABACIACABQAJAHALAAIAGgBIAHgCIAFgEQACgCABgEQgBgEgCgCIgGgDIgJgCIgKgBIgKgCQgGgCgDgCQgEgCgDgEQgCgFAAgHQAAgEACgEQABgEADgDIAHgFIAHgDIACgCIADgCIACgDIABgEIAAgDIABgCIACgCIACAAIAFAAIADACIAAACIAAADIABAEIADADIAEADIAJADIAHAEQAEACgBADIgBADIgCADIgDACIgDABIgEgCIgFgDIgGgDQgFgBgEAAIgFAAIgHACIgEAEQgCACgBAEQAAAFAFACQAEACAGABIANACQAIAAAFADQAHACAEAEQAEAFABAJQAAAFgCAFIgGAHQgCAEgFACIgJAEIgCABIgDACQgCACAAADIAAAHQgBACgDABIgEAAQgEAAgBgBg");
	this.shape_6.setTransform(50.1,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.price, new cjs.Rectangle(43.6,-8.5,48,16.9), null);


(lib.organiccranberry = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAkQgOgOgBgUQAAgWAPgPQAOgOAVAAQASAAAMAKQALALgBASQAAAGgBACQgCACgHAAIgkAAQgDAAgDgCQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQADgBADAAIATAAIAFgBQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAAAgBQAAgJgGgHQgGgGgKAAQgLAAgFAKQgGAKABAOQgBAOAJAMQAHAKAMAAQAGAAAFgBQAFgCAFgDIAEgDQAFgEACAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAACgCAEIgHAGQgJAHgHADQgIADgJAAQgUAAgNgOg");
	this.shape.setTransform(111.7,1.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdAkQgOgOgBgUQAAgWAPgPQAOgOAWAAQAQAAALAIQAKAIABALQAAAFgDADQgEADgEAAQgGAAgCgDQgDgCgEgIQgCgHgFgDQgDgCgGAAQgKAAgHAIQgGAIAAAPQAAAQAJALQAJALANAAQAFAAAEgBIAIgEIAEgDQAFgEADAAIADABQAAAAABABQAAAAAAABQAAAAAAAAQABABAAAAQgBADgCADIgFAGQgHAHgJADQgIADgKAAQgTAAgNgOg");
	this.shape_1.setTransform(101.7,1.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAVAxIgBgFIAAgGIAAgBIgBAAIgDACIgCACQgEAFgGACQgFACgHAAQgHAAgHgCQgGgEgEgEQgFgGgCgIQgCgHAAgVIAAgGIAAgHIAAgCQAAgIgBgCQgBgCgDgBIgEgBQgGgCAAgEQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQACgDAHgCIANgDIAKgBQABAAABAAQAAAAABAAQAAAAABABQAAAAAAAAIABAHIAAADIgBAkQAAAUAEAHQAEAHAKABQAKAAAFgKQAFgKAAgXIAAgIQAAgHgBgCQgBgCgDgBIgEgBQgGgCAAgEQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAIAJgFIANgDIAKgBQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABACAAAFIAAAFIgBAnIAAAQIABAGQAAAFAFACIACAAQAGACAAADQAAABAAAAQgBABAAAAQAAABAAAAQgBABAAAAIgGADIgOAFIgKABQgBAAAAAAQgBAAgBAAQAAAAAAAAQgBgBAAAAg");
	this.shape_2.setTransform(90.8,1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AARAtIgFgEIgEABQgLAJgMgBQgOAAgJgIQgJgIAAgNQAAgQAMgIQALgIAUAAQAEAAADABQACABAAAFQAAAEgGAAQgJAAgGAFQgGAFAAAHQAAAJAFAEQAFAFAIgBQAJAAAEgDQAEgFAAgKIAAgkQAAgIgEgFQgDgEgGgBQgFAAgEACIgIAHIgCACQgGAIgGAAQgEAAgCgCQgDgDAAgEQAAgJALgHQAMgFARAAQAKAAAIACQAHADAFAFQADAEABAGQABAGAAAOIAAAeIABAIQAAABAAAAQABABAAAAQAAABABAAQAAAAABABIADAAQAGACAAADQAAAFgHAEQgGADgJAAQgEABgFgGg");
	this.shape_3.setTransform(80.1,1.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXBGQgLgCgHgEQgDgDgDgIQgCgIAAgLQAAgFABgCQACgCADgBQAFABAEAIIADAFQAGAKAHAFQAHAFAKAAQAKAAAHgHQAIgGAAgIQAAgOgcgMIgDgCQgYgJgHgJQgIgJAAgNQAAgRANgLQANgMAUAAIALABIANADIAEgCIADgBIAEACIAEAEIAFANQACAGAAAFQAAADgBACQgBAAAAABQAAAAgBAAQAAAAgBAAQgBABAAAAQgGgBgEgGIgCgCQgFgHgHgDQgGgEgIAAQgKAAgGAFQgHAFAAAIQAAAIAGAGQAFAFAUAJIAEABQARAIAIAGQAFAEADAHQACAHAAAIQAAATgNALQgOALgYAAQgLAAgLgCg");
	this.shape_4.setTransform(69.2,-0.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgsBAQgFgEAAgGQAAgFAEgEQADgDAFAAIAEABIADACIADADQACAEACAAQAFAAAFgHQAFgHAAgIQAAgIgHgPIgBgCIgPghIgJgTQgCgEgFgCIgFgDIgBgDQAAgFAFgBQAFgCAOAAQAOAAAFACQAFABAAAEIgBADIgBACIgEABQgEACAAACIACAHIAIATIAHASQADAFABAAIADgFIAHgPIAHgTIACgJQAAgDgGgDQgFgDAAgDQAAgDAEgBQAFgCALAAQALAAAEACQAFABAAAEQAAAEgGABIgEABQgFADgHARIgCAHIgNAeQgQApgJAMQgKAMgOAAQgHAAgFgEg");
	this.shape_5.setTransform(53.6,3.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcAwQgFgBAAgFQAAgDAEgCIADgBQADgBABgDIABgLIAAgGIgBgJIAAgFIAAgWQgBgGgCgBIgFgBQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAGgEIANgFIAJgBQAFAAABANIAAACIAAABQAFgIAGgFQAFgDAGAAQAGAAAEADQAEAFAAAGQAAAHgDAEQgDAEgFAAIgFgBIgEgDIgCgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAQgGAAgDAJQgCAJAAAcIABANQABAEACABIAEACQAGACAAAEQAAADgFACQgGABgMABQgPgBgEgBg");
	this.shape_6.setTransform(45.2,1.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgcAwQgFgBAAgFQAAgDAEgCIADgBQADgBABgDIABgLIAAgGIgBgJIAAgFIAAgWQgBgGgCgBIgFgBQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAGgEIANgFIAJgBQAFAAABANIAAACIAAABQAFgIAGgFQAFgDAGAAQAGAAAEADQAEAFAAAGQAAAHgDAEQgDAEgFAAIgFgBIgEgDIgCgEQgBgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAQgGAAgDAJQgCAJAAAcIABANQABAEACABIAEACQAGACAAAEQAAADgFACQgGABgMABQgPgBgEgBg");
	this.shape_7.setTransform(37.9,1.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgeAkQgOgOgBgUQABgWAOgPQAOgOAVAAQASAAAMAKQALALgBASQAAAGgBACQgCACgHAAIgkAAQgDAAgDgCQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBQADgBADAAIATAAIAFgBQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAAAgBQAAgJgGgHQgGgGgKAAQgLAAgFAKQgGAKABAOQgBAOAJAMQAHAKAMAAQAGAAAFgBQAFgCAFgDIAEgDQAFgEACAAQAAAAABAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAABQAAAAABAAQAAABAAAAQAAABAAAAQAAACgCAEIgHAGQgJAHgHADQgIADgJAAQgUAAgNgOg");
	this.shape_8.setTransform(28.9,1.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNBGQgHgDgGgEIgGAEIgGACIgDgBIgDgCIAAgBQADgEABgIQACgJAAgWIAAgVIAAgVIgBgYQAAgGgDgBIgFgCQgGgBAAgEQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBIAJgEIALgDIAKgCQAEABABABQABABABAEIgBAFIAAAcIAAAqIAAAaQgBAOAFAEQAEAFALAAQAMAAAGgKQAHgLAAgRQAAgQgHgIQgGgJgMAAIgCAAIgCABQgHAAAAgHQAAgFAHgDQAGgDAIABQASAAALAMQALANAAAUQAAAYgOAPQgNAPgXAAQgIAAgJgCg");
	this.shape_9.setTransform(17.7,-0.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgvAwQgEgBAAgFQAAgDAEgCIADgBQACgBABgDIABgLIAAgGIAAgJIAAgIIAAgUQgBgFgCgBIgFgBQgGgCAAgEQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAIAGgEIAOgFIAKgBQABAAAAAAQABAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAABIAAAGIAAABIABAAIABAAIAAAAIACgCIACgBQALgLALABQAHAAAGACQAHAEAEAEQAFAGACAHQABAIAAAPIAAAMIAAAGIAAAGIABAKQABADADABIACABQAFACAAADQAAAEgFACQgEABgPAAIgSgBQgFgCAAgDQAAgEAFgCIAEgCQACgBABgEIABgOQAAgegEgIQgEgIgKAAQgEAAgFADQgFAEgCAEQgCAEgBAIIgBAaQAAAKABADQAAAAAAABQAAAAABABQAAAAABABQAAAAABAAIADACQAFACAAAEQAAADgFACQgEABgNABQgPgBgFgBg");
	this.shape_10.setTransform(6.7,1.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AARAtIgFgEIgEABQgLAJgMgBQgOAAgJgIQgJgIAAgNQAAgQAMgIQALgIAUAAQAEAAADABQACABAAAFQAAAEgGAAQgJAAgGAFQgGAFAAAHQAAAJAFAEQAFAFAIgBQAJAAAEgDQAEgFAAgKIAAgkQAAgIgEgFQgDgEgGgBQgFAAgEACIgIAHIgCACQgGAIgGAAQgEAAgCgCQgDgDAAgEQAAgJALgHQAMgFARAAQAKAAAIACQAHADAFAFQADAEABAGQABAGAAAOIAAAeIABAIQAAABAAAAQABABAAAAQAAABABAAQAAAAABABIADAAQAGACAAADQAAAFgHAEQgGADgJAAQgEABgFgGg");
	this.shape_11.setTransform(-4,1.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcAwQgFgBAAgFQAAgDAEgCIADgBQADgBABgDIABgLIAAgGIgBgJIAAgFIAAgWQgBgGgCgBIgFgBQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAGgEIANgFIAJgBQAFAAABANIAAACIAAABQAFgIAGgFQAFgDAGAAQAGAAAEADQAEAFAAAGQAAAHgDAEQgDAEgFAAIgFgBIgEgDIgCgEQAAgBgBAAQAAgBAAAAQgBAAAAAAQAAAAgBAAQgGAAgDAJQgCAJAAAcIABANQABAEACABIAEACQAGACAAAEQAAADgFACQgGABgMABQgPgBgEgBg");
	this.shape_12.setTransform(-12.7,1.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOBDQgNgEgKgJQgLgKgGgPQgGgOAAgQQAAgOAEgLQAEgMAIgJQAJgMAOgGQANgGAQAAIALABIATAEIACgBIAIgBIADABIACACQADAGACAHQACAHAAAGQAAAEgBACQgBABAAAAQgBABAAAAQgBAAAAAAQgBAAgBAAQgEAAgHgIIgGgHQgFgGgIgCQgIgDgJAAQgSAAgLANQgLAMAAAXQAAAcAOASQAOASAUAAQAJAAAHgCQAIgDAFgFIAEgFQAEgGADAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAABQACACAAAFQAAAJgDAFQgCAFgEAAIgBAAIgCAAQgJAFgJACQgJACgKAAQgNAAgNgFg");
	this.shape_13.setTransform(-23.2,-0.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeAkQgOgOAAgUQAAgWAPgPQAOgOAVAAQAQAAALAIQALAIAAALQAAAFgDADQgDADgFAAQgFAAgDgDQgCgCgDgIQgEgHgDgDQgEgCgGAAQgLAAgFAIQgHAIAAAPQAAAQAJALQAJALANAAQAFAAAEgBIAIgEIAEgDQAFgEADAAIADABQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAADgCADIgFAGQgIAHgHADQgJADgJAAQgUAAgOgOg");
	this.shape_14.setTransform(-40.1,1.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgRBFQgEgBAAgFQAAgDAEgCIADgBQACgBABgDIABgLIAAgGIAAgJIAAgJIAAgTQgBgFgCgBIgFgBQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAABAAIAFgEIAPgFIAJgBQABAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABACABAFIAAAFIgBAFIAAAYIAAAAIgBAXIABAOQAAADADABIADACQAGACgBAEQABADgGACQgEABgNABQgNgBgGgBgAgLgwQgEgDAAgFQAAgGAEgEQAFgDAGgBQAGABAEADQAEADAAAFQAAAGgFADQgEAFgGAAQgGgBgEgDg");
	this.shape_15.setTransform(-47.9,-0.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgvAwQgEgBAAgFQAAgDAEgCIADgBQACgBABgDIABgLIAAgGIAAgJIAAgIIAAgUQgBgFgCgBIgFgBQgGgCAAgEQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAIAGgEIAOgFIAKgBQABAAAAAAQABAAABAAQAAABAAAAQABAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAABAAABIAAAGIAAABIABAAIABAAIAAAAIACgCIACgBQALgLALABQAHAAAGACQAHAEAEAEQAFAGACAHQABAIAAAPIAAAMIAAAGIAAAGIABAKQABADADABIACABQAFACAAADQAAAEgFACQgEABgPAAIgSgBQgFgCAAgDQAAgEAFgCIAEgCQACgBABgEIABgOQAAgegEgIQgEgIgKAAQgEAAgFADQgFAEgCAEQgCAEgBAIIgBAaQAAAKABADQAAACADABIADACQAFACAAAEQAAADgFACQgEABgNABQgPgBgFgBg");
	this.shape_16.setTransform(-56.4,1.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AARAtIgFgEIgEABQgLAJgMgBQgOAAgJgIQgJgIAAgNQAAgQAMgIQALgIAUAAQAEAAADABQACABAAAFQAAAEgGAAQgJAAgGAFQgGAFAAAHQAAAJAFAEQAFAFAIgBQAJAAAEgDQAEgFAAgKIAAgkQAAgIgEgFQgDgEgGgBQgFAAgEACIgIAHIgCACQgGAIgGAAQgEAAgCgCQgDgDAAgEQAAgJALgHQAMgFARAAQAKAAAIACQAHADAFAFQADAEABAGQABAGAAAOIAAAeIABAIQAAABAAAAQABABAAAAQAAABABAAQAAAAABABIADAAQAGACAAADQAAAFgHAEQgGADgJAAQgEABgFgGg");
	this.shape_17.setTransform(-67.1,1.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgjA/QgMgIAAgKQAAgFACgDQADgDAFAAQAEgBADADIADAHQACAHAGAEQAHAEALAAQAMAAAJgFQAIgFAAgHQAAgFgDgCQgDgDgGAAIgLABIgOABQgRAAgKgGQgJgGAAgHQAAgGADgEQAEgEAHgEQgGgFgDgGQgDgHAAgHQAAgQAMgKQAMgKASAAIAKABIAOACIAIgCIAKgGIAEAEIABADQAAAEgEAEQgDADgFAEIADAHIABAIQAAAQgMAKQgMAJgSAAIgKgBIgJgBIgDAEIgBADQAAAFAEACQAFACAKAAIANgBIAPgBQAOgBAHAGQAHAFAAAKQAAAQgPALQgPAKgWgBQgTAAgMgHgAgPgvQgFAGAAAKQAAAJAFAGQAFAHAIgBQAHABAFgHQAGgFAAgKQAAgKgGgGQgFgGgHgBQgIABgFAGg");
	this.shape_18.setTransform(-77.1,2.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgcAwQgFgBAAgFQAAgDAEgCIADgBQADgBABgDIABgLIAAgGIgBgJIAAgFIAAgWQgBgGgCgBIgFgBQgFgCAAgEQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAGgEIANgFIAJgBQAFAAABANIAAACIAAABQAFgIAGgFQAFgDAGAAQAGAAAEADQAEAFAAAGQAAAHgDAEQgDAEgFAAIgFgBIgEgDIgCgEQgBgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAQgGAAgDAJQgCAJAAAcIABANQABAEACABIAEACQAGACAAAEQAAADgFACQgGABgMABQgPgBgEgBg");
	this.shape_19.setTransform(-86,1.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgUBFQgLgDgJgHQgOgKgIgQQgHgQAAgSQAAgfATgUQAUgTAeAAQANAAALAEQAKADAJAHQANALAHAQQAHAQAAARQAAAMgDAKQgDALgGAJQgKANgPAHQgPAHgRAAQgLAAgKgDgAgfgsQgLANAAAWQAAAdANAUQANATAUAAQARAAALgOQALgNAAgWQAAgdgOgTQgNgUgTAAQgSAAgKAOg");
	this.shape_20.setTransform(-97.6,-0.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.organiccranberry, new cjs.Rectangle(-107.3,-14.4,226.3,27), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARAjIgRg3IgQA3IgLAAIgVhGIALAAIAQA4IARg4IAJAAIARA4IAQg4IALAAIgVBGg");
	this.shape.setTransform(90.5,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgHgCgFgFQgFgFgDgHQgCgHAAgIQAAgIACgGQADgHAFgFQAFgFAHgDIAHgCIAHAAQAIAAAHACIAGAEIAGAEQAFAFADAHQACAGAAAIQAAAIgCAHQgDAHgFAFIgGAEIgGADQgHADgIAAIgHgBgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFAEAEQADAEAFACQAFACAFAAQAGAAAFgCQAFgCAEgEQADgEACgFQACgFAAgGQAAgFgCgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_1.setTransform(81.3,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AASAjIglg4IAAA4IgKAAIAAhGIANAAIAkA5IAAg5IAKAAIAABGg");
	this.shape_2.setTransform(73.2,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANAjIgRgfIgKAAIAAAfIgKAAIAAhGIAXAAQAEABAEABIAIADQAEACACAEQACAEAAAFQAAAIgFAFQgCACgEABIgGACIATAggAgOgDIALAAIAGgBIAFgCQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAAgBQACgBAAgEQAAgDgCgCIgDgEIgFgCIgFAAIgMAAg");
	this.shape_3.setTransform(64.1,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWAjIAAhGIAsAAIAAAJIgiAAIAAAWIAgAAIAAAHIggAAIAAAXIAjAAIAAAJg");
	this.shape_4.setTransform(58,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeAjIAAhGIAYAAQAGAAAHACQAHADAFAEQAGAEADAHIADAHIAAAIIAAAIIgDAIIgEAGIgFAFQgFAEgHADIgNABgAgUAbIAMAAQAHAAAEgCIAJgFQAEgDADgGIABgFIABgGIgBgFIgBgFQgDgFgEgEIgJgFQgEgBgHgBIgMAAg");
	this.shape_5.setTransform(51.1,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AANAjIgRgfIgKAAIAAAfIgKAAIAAhGIAXAAQAEABAEABIAIADQAEACACAEQACAEAAAFQAAAIgFAFQgCACgEABIgGACIATAggAgOgDIALAAIAGgBIAFgCQAAAAABgBQAAAAABAAQAAgBABAAQAAgBAAgBQACgBAAgEQAAgDgCgCIgDgEIgFgCIgFAAIgMAAg");
	this.shape_6.setTransform(44.4,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgHAkIgHgCQgHgCgFgFQgFgFgDgHQgCgHAAgIQAAgIACgGQADgHAFgFQAFgFAHgDIAHgCIAHAAQAIAAAHACIAGAEIAGAEQAFAFADAHQACAGAAAIQAAAIgCAHQgDAHgFAFIgGAEIgGADQgHADgIAAIgHgBgAgKgZQgFACgDAEQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFAEAEQADAEAFACQAFACAFAAQAGAAAFgCQAFgCADgEQAEgEACgFQACgFAAgGQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgFAAgFADg");
	this.shape_7.setTransform(36.9,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(30.6,-8.5,66.9,16.3), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalebackground = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0D6E47").s().p("A6bFUIAAqnMA04AAAIAAKng");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalebackground, new cjs.Rectangle(-169.2,-34,338.5,68), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A6Fj2MA0LAAAIAAHuMg0LAAAg");
	this.shape.setTransform(0,0,0.955,0.99);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-25.5,321,51), null);


(lib.ctavideodark = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("Al3A8IAAh3ILvAAIAAB3g");
	this.shape.setTransform(64.9,0,1.134,1.552);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctavideodark, new cjs.Rectangle(22.3,-9.3,85.3,18.7), null);


(lib.ctarectangleorange = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("Al2BNIAAiZILtAAIAACZg");
	this.shape.setTransform(57.3,0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangleorange, new cjs.Rectangle(19.8,-7.6,75,15.5), null);


(lib.classicturkeydinnerfor8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIAJQgFgEAAgFQAAgFAFgEQAEgDAEAAQAGAAAEADQADAEAAAFQAAAFgDAEQgEAFgGAAQgEAAgEgFg");
	this.shape.setTransform(172.2,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdAzQgLgJAAgOQAAgJAGgIQAFgIAMgFQgJgFgFgHQgGgHAAgIQAAgOALgIQALgIARAAQAQAAAKAHQAKAIAAALQAAAJgFAGQgGAHgLAGQANAFAGAIQAGAJAAAKQAAAOgLAKQgMAJgRAAQgSAAgMgJgAgQAOQgEAFAAAHQAAAJAHAHQAHAHAIAAQAIAAAFgFQAFgFAAgHQAAgIgGgHQgHgGgNgGQgHAEgDAFgAgKgsQgEAEAAAGQAAAGAFAFQAEAFAKAGQAGgFADgFQADgEAAgFQAAgHgFgFQgFgFgHAAQgFAAgFAEg");
	this.shape_1.setTransform(165,0.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZArQgEgCAAgEQAAgCADgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgFIAAgUQgBgFgCgBIgFgCQgEgBAAgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAFgDIAMgDIAIgCQAEAAABAMIAAABIAAABQAFgHAFgEQAEgDAFAAQAHAAADADQADAEABAGQgBAGgCADQgDAEgEAAIgFgBIgDgDIgCgDIgDgCQgGAAgCAIQgCAIAAAaQAAAHABAEQABAEACABIADABQAFACABADQAAADgFACQgFABgLAAQgNAAgEgBg");
	this.shape_2.setTransform(152.4,2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAgQgMgNAAgTQAAgTANgMQANgNATAAQASAAAMAMQAMAMAAATQAAATgNAOQgMANgTAAQgSAAgNgNgAgPgZQgGAHAAALQAAARAIAMQAHALAJAAQAIAAAGgIQAFgHAAgLQAAgQgHgLQgIgMgJAAQgJAAgEAHg");
	this.shape_3.setTransform(144,2.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXA+QgFgBAAgEQAAgCAFgCIABgBIAEgEIABgKIAAgIIAAgpIgKAAIgDgBIgBgDIAAgDIABgDIADgBIAJAAIgBgGIgBgHQABgNAHgHQAJgHANAAQAKAAAGAEQAGAFAAAGQAAAFgCACQgDACgEAAQgDAAgBgCIgFgDIgBgDQgDgGgFAAQgDAAgCACQgBACgBADIACAKQACAHAAAGIAMAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABADIAAADIgBADIgDABIgMAAIAAArIAAAPQABADACABIAEABQAEACAAAEQABADgFABQgEABgLAAQgOAAgDgBg");
	this.shape_4.setTransform(137.5,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZArQgFgCABgEQAAgCADgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgFIAAgUQgCgFgCgBIgDgCQgFgBgBgDQAAgBABAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAFgDIAMgDIAIgCQAEAAABAMIAAABIAAABQAFgHAFgEQAFgDAEAAQAGAAAEADQAEAEAAAGQAAAGgDADQgDAEgFAAIgEgBIgDgDIgDgDIgCgCQgFAAgDAIQgCAIAAAaQAAAHABAEQABAEACABIAEABQAEACAAADQABADgFACQgFABgLAAQgNAAgEgBg");
	this.shape_5.setTransform(126.4,2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgbAhQgNgNAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgCQAFgBAEgDIADgCQAEgEADAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAACgCADIgGAHQgHAFgHADQgHADgJAAQgRAAgMgMg");
	this.shape_6.setTransform(118.4,2.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqArQgEgCAAgEQAAgCAEgCIACgBQACgBACgDIABgKIAAgFIAAgHIAAgIIgBgSQgBgEgCgBIgEgCQgFgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBIAGgDIAMgEIAJgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIABAEIAAAGIAAABIAAAAIABAAIAAAAIACgCIACgCQAKgIAKAAQAGAAAFACQAHADADAFQAEAEACAHQABAGAAAOIAAALIAAAGIAAAFIABAIQABADACABIADABQAEACAAACQAAAEgEACQgEABgNAAQgNAAgEgBQgEgCAAgDQAAgDAEgCIADgBQACgBACgEIABgNQgBgbgDgHQgDgHgKAAQgEAAgEADQgEADgCAEQgCAEgBAHIAAAXQAAAIAAADQABABAAAAQAAABAAAAQABABAAAAQABAAAAABIADABQAEACAAADQAAADgEACQgEABgLAAQgNAAgFgBg");
	this.shape_7.setTransform(108.7,2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqArQgEgCAAgEQAAgCAEgCIADgBQABgBABgDIABgKIAAgFIAAgHIAAgIIgBgSQAAgEgCgBIgEgCQgFgBAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAAAgBIAGgDIANgEIAIgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIABAEIAAAGIAAABIABAAIAAAAIABAAIACgCIABgCQAKgIAJAAQAGAAAHACQAFADAFAFQADAEACAHQACAGAAAOIAAALIAAAGIAAAFIABAIQAAADACABIACABQAFACAAACQAAAEgEACQgEABgOAAQgMAAgDgBQgFgCAAgDQAAgDAFgCIADgBQABgBABgEIABgNQABgbgEgHQgDgHgKAAQgDAAgEADQgFADgCAEQgCAEAAAHIgCAXQAAAIACADQAAABAAAAQAAABAAAAQABABAAAAQAAAAABABIADABQAFACAAADQAAADgFACQgEABgMAAQgNAAgEgBg");
	this.shape_8.setTransform(98.4,2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgPA+QgEgCAAgEQAAgCAEgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgJIgBgRQgBgEgCgBIgEgCQgFgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIAFgDIANgEIAIgBQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIABAGIAAAFIAAAEIgBAVIAAAAIAAAWIAAALQABAEACABIADABQAFACAAADQAAADgFACQgEABgLAAQgMAAgFgBgAgKgrQgEgDAAgEQAAgFAFgEQAEgDAFAAQAFAAAEADQADADAAAFQAAAFgEADQgEADgFAAQgFAAgEgDg");
	this.shape_9.setTransform(90.7,0.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgSA+IgLAAIgHAAIgHABQgLAAgDgCQgDgBAAgEQAAgDAEgCIAGgDQABgCABgNIAAghIAAggQgBgNgBgCIgGgDQgEgCAAgDQAAgEADgBQAEgBAKAAIAIAAIAJAAIALAAIAKAAQAfAAASAQQARARAAAeQAAAdgSAQQgSAPghABgAgSgxQgEACgBADIgCANIAAAaIAAAhIACAQQABACAFACQAGACAIAAQATAAAKgMQAKgMAAgYQAAgZgLgNQgMgOgUAAIgLABg");
	this.shape_10.setTransform(81.6,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgnA5QgEgEgBgFQAAgEADgDQAEgEAEAAIAEABIADACIACADQABABAAABQAAAAABABQAAAAABABQAAAAABAAQAEAAAFgHQAEgGAAgHQAAgHgGgOIgBgCIgNgdIgIgRQgCgDgFgCIAAgBIgEgCIgBgDQAAgEAEgBQAFgCANAAQAMAAAFACQADABAAADIAAADIgCACIgCABQgBABgBAAQgBAAAAABQgBAAAAAAQAAABAAAAIACAHIAHARIAGAQQACAEACAAQAAAAAAAAQAAAAABgBQAAAAABgBQAAgBABgBIAFgNIAGgSIACgIQAAgCgEgDQgFgDgBgCQAAgDAFgBQAEgCAJAAQALAAAEACQADABAAADQAAAEgFABIgEABQgFADgFAOIgCAHIgLAbQgPAkgIALQgJALgMAAQgHAAgEgEg");
	this.shape_11.setTransform(66.1,3.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbAhQgNgNAAgTQAAgTANgNQANgNASAAQARAAAKAJQAKAKAAAQQAAAFgCACQgCACgGgBIggAAIgFgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAFgBIARAAIAEgBIABgCQAAgJgFgGQgGgFgIAAQgJAAgFAJQgFAJAAANQAAAMAHAKQAGAKAKAAIALgCQAFgBAEgDIADgCQAEgEADAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAACgCADIgGAHQgHAFgHADQgHADgJAAQgRAAgMgMg");
	this.shape_12.setTransform(57.2,2.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAcA/IgDgBQgFgBgIgKIgDgFIgBgCQgVgbgCAAIgBAAIgBAEIAAAEIABASIACAHIAFADQAEABAAADQAAAEgEABQgFACgLgBQgNABgFgCQgDgBAAgFQAAgCADgCIADAAQACgCABgEIABgOIAAgMIAAgMIAAgKIAAghQgBgHgBgCIgGgCIgCgBIgEgBIAAgDQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAQACgCAGgCIAMgEIAJgBQABABAAAAQABAAAAAAQABAAAAAAQAAABAAAAIABAGIAAAQIgBAWIAAAWIABAEIABABIAEgCIAGgGIAIgHIACgEQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgDgCABgDQgBgEAEgBQAEgCANAAQAIAAAEACQAEABAAAEQAAAEgHACQgGABgDACQgDABgHAHIgBABIgDAEIgBACQAAABAHAKIABABIAPASIAJAKIAIADQAGACAAADQAAAEgEACQgEACgJgBg");
	this.shape_13.setTransform(48.1,0.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgZArQgEgCAAgEQAAgCADgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgFIgBgUQAAgFgCgBIgFgCQgEgBAAgDQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBIAFgDIAMgDIAIgCQAEAAABAMIAAABIAAABQAFgHAFgEQAEgDAFAAQAHAAADADQADAEABAGQgBAGgCADQgDAEgEAAIgFgBIgDgDIgCgDIgDgCQgGAAgCAIQgCAIAAAaQAAAHABAEQABAEACABIADABQAFACABADQAAADgFACQgFABgLAAQgNAAgEgBg");
	this.shape_14.setTransform(39.9,2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AATArIgBgDIAAgGIgBgBIgDACIgBABQgEAFgFABQgFACgGAAQgHAAgFgCQgGgCgEgFQgEgFgCgGQgBgIAAgRIAAgGIAAgGIAAgCQAAgHgBgCQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAIgEgCQgFAAAAgDQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAgBIAIgDIAMgDIAJgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAIABAGIAAADIgBAhQAAARAEAGQAEAHAIAAQAJAAAFgJQAEgJAAgUIAAgHQAAgGgBgCQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAIgDgCQgFAAAAgDQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAIgEIAMgDIAJgBQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAAAIABAGIAAAFIgBAjIAAAOIABAGQABAEAEABIACAAQAFADAAADIgCACIgFAEIgMADIgKACQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBg");
	this.shape_15.setTransform(31.1,2.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgRA9QgFgBAAgEQAAgDAFgCIAFgDQABgCAAgOIABgoIAAgXIgBgNIgCgEIgEgBIgFAAQgFABgEABIgFAFIgDAFIgDAGIgCADIgEABQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQgCgDABgFQAAgLACgHQADgHAEAAIABAAIASABIAyAAIARgBIABAAQAEAAACAHQAEAHAAALQAAAFgCADQAAABgBAAQAAAAAAABQgBAAgBAAQAAAAgBAAIgCgBIgDgDIgDgGIgCgFQgDgDgEgCQgCgBgHgBIgDAAIgFABQAAABgBAAQAAAAAAAAQAAABgBAAQAAABAAABIAAANIgBAXIABAoQAAAOABACIAGADQAEACAAADQAAAEgEABQgGACgNAAQgNAAgEgCg");
	this.shape_16.setTransform(20.5,0.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaAhQgNgNAAgTQAAgTANgNQANgNATAAQAOAAAKAHQAKAHAAAKQAAAEgDADQgDACgEAAQgEABgDgCQgDgDgDgGQgCgHgEgCQgDgCgFAAQgJgBgGAIQgGAHAAAOQAAAOAIAJQAIALAMAAQAEAAAEgCIAHgDIADgCQAFgFADAAQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIABADIgCAFIgFAGQgHAFgHADQgHADgJAAQgRAAgMgMg");
	this.shape_17.setTransform(5.7,2.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgPA+QgEgCAAgEQAAgCAEgCIADgBQACgBABgDIABgKIAAgFIAAgHIAAgJIgBgRQgBgEgCgBIgEgCQgFgBAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIAFgDIANgEIAIgBQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIABAGIAAAFIAAAEIgBAVIAAAAIAAAWIAAALQABAEACABIADABQAFACAAADQAAADgFACQgEABgLAAQgMAAgFgBgAgKgrQgEgDAAgEQAAgFAFgEQAEgDAFAAQAFAAAEADQADADAAAFQAAAFgEADQgEADgFAAQgFAAgEgDg");
	this.shape_18.setTransform(-1.2,0.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgGAtIgJgBIgDABIgCABIgCgBIgCgBQgCgDgDgGQgCgIAAgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAFABADAGIAEAGQACADAFACQAEACAEAAQAHAAACgDQAEgCAAgGQAAgHgOgGIgEgDQgOgGgFgGQgEgFgBgIQAAgMAJgGQAHgIAMABIAGAAIAGABIAEgCIACAAQAFAAAEAGQAEAHAAAHQAAAEgCACQAAAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEgBIgFgGQgDgFgEgDQgDgCgFAAQgDAAgDADQgEADAAAEQAAAFAEADQACADAKAFIABABQAZAKAAAOQAAAMgKAJQgJAHgOABg");
	this.shape_19.setTransform(-7.4,2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgGAtIgJgBIgDABIgCABIgCgBIgCgBQgCgDgDgGQgDgIABgGQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAQAAgBAAAAQAFABADAGIAEAGQACADAFACQAEACAFAAQAFAAAEgDQADgCAAgGQAAgHgOgGIgEgDQgOgGgFgGQgEgFgBgIQABgMAHgGQAIgIAMABIAGAAIAGABIAEgCIACAAQAFAAAEAGQAEAHAAAHQAAAEgBACQgBAAAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAIgEgBIgFgGQgDgFgDgDQgEgCgEAAQgFAAgCADQgEADAAAEQAAAFAEADQADADAJAFIABABQAYAKAAAOQAAAMgJAJQgJAHgOABg");
	this.shape_20.setTransform(-14.8,2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAPApIgEgFIgEACQgKAHgKAAQgNAAgIgHQgIgIAAgMQAAgOAKgGQAKgIASAAQAEAAACABQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAEgFAAQgIAAgGAFQgFADAAAIQAAAGAFAFQAEAEAIAAQAHAAAEgEQAEgDAAgJIAAghQAAgHgEgEQgDgFgFAAQgEABgEACQgEACgDADIgCADQgFAGgGAAQgDAAgCgCQgDgCAAgEQAAgIALgFQAKgGAPAAQAJAAAHADQAHACAEAEQACAEABAFIABASIAAAbIABAHQAAABABAAQAAABAAAAQAAAAABABQAAAAABAAIACABQAGABAAADQAAAEgGAEQgGADgIAAQgDAAgFgEg");
	this.shape_21.setTransform(-23,2.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgOA+QgEgBAAgFQAAgCAEgBIAEgDQACgCAAgEIAAgRIAAgOIAAgPIAAgHQAAgWgBgGQAAgHgCgBIgFgBQgFgCAAgDQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQACgCAGgCIALgEIAIgBQABABABAAQAAAAABAAQAAAAAAAAQABABAAAAIABAGIAAAHIgBA8IABAeQAAAGACACIAEADQAFABAAADQgBAEgEABQgEACgLgBQgMABgFgCg");
	this.shape_22.setTransform(-30.2,0.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNA9QgLgFgJgIQgKgJgFgNQgFgMAAgPQAAgMADgLQAEgJAHgJQAIgKAMgGQAMgFAOgBIAKABIARAEIACgBIAGgBIADABIADADIAEALIACALIgBAGQgBAAAAABQgBAAAAAAQAAAAgBAAQgBAAAAAAQgEAAgHgHIgFgHQgFgEgHgCQgHgDgIAAQgQAAgKAMQgJALAAAUQAAAZAMAQQAMARASAAQAIAAAHgDQAGgCAFgEIAEgGQAEgEACAAQABAAAAAAQABAAABAAQAAAAAAABQABAAAAABIABAGQAAAIgCAFQgCAFgEgBIgBAAIgBAAQgIAEgIACQgIACgJAAQgMAAgMgDg");
	this.shape_23.setTransform(-38.4,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.classicturkeydinnerfor8, new cjs.Rectangle(-46.4,-12.2,223.2,24.6), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.WFM_Logo_White_RGBai("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.1,0,0.223,0.223,0,0,0,175.2,174.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(-39,-39,78,78), null);


(lib.ctadarkrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer 1
	this.instance = new lib.ctavideodark();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(22.3,-9.3,85.3,18.7);


// stage content:
(lib.mobileleaderboardclassicturkeydinnershort = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_40 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_56 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(40).call(this.frame_40).wait(16).call(this.frame_56).wait(4));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.7,25.5,1.558,0.078,0,0,0,0.2,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(60));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(60));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(161,25.5,1.954,0.085,0,0,0,0.3,0);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.1,scaleX:1.95,scaleY:0.08,x:160.1,y:25,alpha:0},9).wait(51));

	// logo
	this.instance_2 = new lib.logo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(39.5,24.3,0.762,0.762,0,0,0,0.1,0.1);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({regX:0,regY:0,scaleX:0.05,scaleY:0.05},0).to({regX:0.1,regY:0.1,scaleX:0.82,scaleY:0.82,alpha:1},6,cjs.Ease.get(1)).to({scaleX:0.76,scaleY:0.76},7,cjs.Ease.get(1)).wait(38));

	// order-now
	this.instance_3 = new lib.ordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(114.9,36.2);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(40).to({alpha:1},10).wait(10));

	// cta-rollover
	this.cta_rollover = new lib.ctadarkrectangle();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(115,36.2);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(40).to({alpha:1},10).wait(10));

	// cta-rectangle
	this.instance_4 = new lib.ctarectangleorange();
	this.instance_4.parent = this;
	this.instance_4.setTransform(115.1,36.4,1.133,1.174,0,0,0,0,0.1);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(40).to({alpha:1},10).wait(10));

	// organic-cranberry-sauce
	this.instance_5 = new lib.organiccranberry();
	this.instance_5.parent = this;
	this.instance_5.setTransform(185.4,24.3);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(60));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AyUIzIAAxkMAw1AAAIAARkg");
	mask.setTransform(195.3,22.4);

	// class-turkey-dinner-for-8
	this.instance_6 = new lib.classicturkeydinnerfor8();
	this.instance_6.parent = this;
	this.instance_6.setTransform(123.7,13.3);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(22).to({x:-84.3},0).to({x:128.7,alpha:1},10,cjs.Ease.get(1)).to({x:123.7},8,cjs.Ease.get(1)).wait(20));

	// price
	this.instance_7 = new lib.price();
	this.instance_7.parent = this;
	this.instance_7.setTransform(38.5,36.4);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(40).to({alpha:1},10).wait(10));

	// kale-background
	this.instance_8 = new lib.kalebackground();
	this.instance_8.parent = this;
	this.instance_8.setTransform(162.3,28.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(60));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(153.1,19.1,338.5,68);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;